const scalarsFromGraphQLScalarsPackage = `#graphql
scalar AccountNumber
scalar BigInt
scalar Byte
scalar CountryCode
scalar Cuid
scalar Currency
scalar DID
scalar Date
scalar DateTime
scalar Duration
scalar EmailAddress
scalar GUID
scalar HSL
scalar HSLA
scalar HexColorCode
scalar Hexadecimal
scalar IBAN
scalar IP
scalar IPv4
scalar IPv6
scalar ISBN
scalar ISO8601Duration
scalar JSON
scalar JSONObject
scalar JWT
scalar Latitude
scalar LocalDate
scalar LocalEndTime
scalar LocalTime
scalar Locale
scalar Long
scalar Longitude
scalar MAC
scalar NegativeFloat
scalar NegativeInt
scalar NonEmptyString
scalar NonNegativeFloat
scalar NonNegativeInt
scalar NonPositiveFloat
scalar NonPositiveInt
scalar ObjectID
scalar PhoneNumber
scalar Port
scalar PositiveFloat
scalar PositiveInt
scalar PostalCode
scalar RGB
scalar RGBA
scalar RoutingNumber
scalar SafeInt
scalar SemVer
scalar Time
scalar TimeZone
scalar Timestamp
scalar URL
scalar USCurrency
scalar UUID
scalar UnsignedFloat
scalar UnsignedInt
scalar UtcOffset
scalar Void
`;
